### ISSUE TITLE
Kafka compression

### ISSUE THREAD

**Issue by pdepaepe** [jedisct1/flowgger#3]
Please consider kafka compression option. About Snappy vs Gzip, this quite old article might be useful

http://nehanarkhede.com/2013/03/28/compression-in-kafka-gzip-or-snappy/

Thanks

**Comment by jedisct1** [comment]
Kafka's protocol is horrible and ruined my weekend, but it's done.

``` toml
kafka_compression = "none"
kafka_compression = "gzip"
kafka_compression = "snappy"
```
